export const componentTypes = [
  'Sensor',
  'Actuador',
  'Display/HMI',
  'Dispositivo de mando',
  'Equipo de control',
  'Protección / Potencia',
  'Drive / Motion',
  'Red / Comunicación',
  'Alimentación / Energía',
  'Infraestructura / Montaje',
  'Instrumentación de proceso',
] as const

export type AutomationComponentType = (typeof componentTypes)[number]

export interface AutomationComponent {
  type: AutomationComponentType
  category: string
  subcategory: string
  name: string
  signal: string
  notes: string
  application: string
  diagramContext: string
}

export const automationComponents: AutomationComponent[] = [
  // ---- Sensor ----
  // Presencia / Posición
  {
    type: 'Sensor',
    category: 'Presencia / Posición',
    subcategory: 'Proximidad',
    name: 'Inductivo',
    signal: 'Salida digital 24 V, NPN/PNP',
    notes: 'Detecta metal a corta distancia, muy usado en finales de posición',
    application: 'Detección de presencia o posición de piezas metálicas en una cinta transportadora',
    diagramContext: 'Plano de control / plano de campo (sensores discretos)',
  },
  {
    type: 'Sensor',
    category: 'Presencia / Posición',
    subcategory: 'Proximidad',
    name: 'Capacitivo',
    signal: 'Salida digital 24 V, NPN/PNP',
    notes: 'Detecta plásticos, líquidos, grano, etc.',
    application: 'Detección de nivel de material a granel o presencia de envases plásticos',
    diagramContext: 'Plano de control / plano de campo (sensores discretos)',
  },
  {
    type: 'Sensor',
    category: 'Presencia / Posición',
    subcategory: 'Proximidad',
    name: 'Ultrasónico',
    signal: 'Salida analógica 4–20 mA / 0–10 V o digital',
    notes: 'Mide distancia sin contacto, útil para nivel o posicionamiento',
    application: 'Medición de distancia a una superficie líquida para control de nivel',
    diagramContext: 'P&ID / plano de instrumentación de proceso',
  },
  {
    type: 'Sensor',
    category: 'Presencia / Posición',
    subcategory: 'Proximidad',
    name: 'Fotoeléctrico barrera',
    signal: 'Salida digital 24 V',
    notes: 'Emisor y receptor separados, detección fiable en distancias medias',
    application: 'Conteo de piezas que atraviesan una cinta transportadora',
    diagramContext: 'Plano de control / plano de campo (sensores discretos)',
  },
  {
    type: 'Sensor',
    category: 'Presencia / Posición',
    subcategory: 'Proximidad',
    name: 'Fotoeléctrico retro-reflectivo',
    signal: 'Salida digital 24 V',
    notes: 'Usa reflector, menos cableado que la barrera',
    application: 'Detección de productos en una línea de envasado usando reflector',
    diagramContext: 'Plano de control / plano de campo (sensores discretos)',
  },
  {
    type: 'Sensor',
    category: 'Presencia / Posición',
    subcategory: 'Proximidad',
    name: 'Fotoeléctrico difuso',
    signal: 'Salida digital 24 V',
    notes: 'Emisor y receptor en el mismo cuerpo, reflexión en el objeto',
    application: 'Detección de presencia de cajas u objetos sobre una mesa de rodillos',
    diagramContext: 'Plano de control / plano de campo (sensores discretos)',
  },
  {
    type: 'Sensor',
    category: 'Presencia / Posición',
    subcategory: 'Final de carrera mecánico',
    name: 'Micro-switch con rodillo o palanca',
    signal: 'Contacto NA/NC',
    notes: 'Limitación física de recorrido, robusto',
    application: 'Detección de tope de recorrido de un carro o eje mecánico',
    diagramContext: 'Plano de control / plano de campo (sensores discretos)',
  },
  {
    type: 'Sensor',
    category: 'Presencia / Posición',
    subcategory: 'Magnético',
    name: 'Reed o efecto Hall',
    signal: 'Salida digital 24 V',
    notes: 'Detección de imán en cilindros neumáticos, puertas, etc.',
    application: 'Detección de posición de émbolo en cilindro neumático con imán',
    diagramContext: 'Plano de control / plano de campo (sensores discretos)',
  },
  {
    type: 'Sensor',
    category: 'Presencia / Posición',
    subcategory: 'Encoder',
    name: 'Encoder incremental rotativo',
    signal: 'Pulsos A/B/Z (5 V o 24 V)',
    notes: 'Mide velocidad y posición relativa de ejes',
    application: 'Medición de velocidad y posición de un motor de eje en máquina',
    diagramContext: 'Plano de control / plano de campo (sensores discretos)',
  },
  {
    type: 'Sensor',
    category: 'Presencia / Posición',
    subcategory: 'Encoder',
    name: 'Encoder absoluto',
    signal: 'Bus industrial o código binario/Gray',
    notes: 'Informa posición absoluta del eje',
    application: 'Posicionamiento absoluto de un eje en máquina de embalaje o robot',
    diagramContext: 'Plano de control / plano de campo (sensores discretos)',
  },
  // Movimiento / Velocidad
  {
    type: 'Sensor',
    category: 'Movimiento / Velocidad',
    subcategory: 'Velocidad',
    name: 'Sensor inductivo con rueda dentada',
    signal: 'Pulsos digitales 24 V',
    notes: 'Mide velocidad de giro de ejes o ruedas',
    application: 'Medición de RPM de un eje usando rueda dentada',
    diagramContext: 'Plano de control / plano de mantenimiento predictivo',
  },
  {
    type: 'Sensor',
    category: 'Movimiento / Velocidad',
    subcategory: 'Vibración',
    name: 'Sensor de vibración industrial',
    signal: '4–20 mA o bus',
    notes: 'Monitorización de estado de rodamientos y motores',
    application: 'Monitorización de vibraciones de motores para mantenimiento predictivo',
    diagramContext: 'Plano de control / plano de mantenimiento predictivo',
  },
  {
    type: 'Sensor',
    category: 'Movimiento / Velocidad',
    subcategory: 'Inclinación',
    name: 'Sensor de inclinación',
    signal: '4–20 mA / 0–10 V / bus',
    notes: 'Control de ángulo en grúas, plataformas, etc.',
    application: 'Control de inclinación de plataforma de elevación',
    diagramContext: 'Plano de control / plano de instrumentación de proceso',
  },
  // Temperatura
  {
    type: 'Sensor',
    category: 'Temperatura',
    subcategory: 'Termopar',
    name: 'Termopar tipo K/J/etc.',
    signal: 'mV, requiere acondicionamiento',
    notes: 'Rangos amplios de temperatura, uso en hornos y procesos',
    application: 'Medición de temperatura en horno industrial de tratamiento térmico',
    diagramContext: 'P&ID / plano de instrumentación de proceso',
  },
  {
    type: 'Sensor',
    category: 'Temperatura',
    subcategory: 'RTD',
    name: 'PT100 / PT1000',
    signal: 'Resistencia variable, entrada específica',
    notes: 'Buena precisión y estabilidad',
    application: 'Control de temperatura de tanque con PT100 y lazo PID',
    diagramContext: 'P&ID / plano de instrumentación de proceso',
  },
  {
    type: 'Sensor',
    category: 'Temperatura',
    subcategory: 'Termistor',
    name: 'NTC/PTC',
    signal: 'Resistencia variable',
    notes: 'Uso en aplicaciones de rango más limitado',
    application: 'Protección térmica en equipos electrónicos o pequeños procesos',
    diagramContext: 'P&ID / plano de instrumentación de proceso',
  },
  // Presión / Caudal
  {
    type: 'Sensor',
    category: 'Presión / Caudal',
    subcategory: 'Presión',
    name: 'Transductor de presión',
    signal: '4–20 mA / 0–10 V',
    notes: 'Mide presión en sistemas hidráulicos y neumáticos',
    application: 'Medición de presión en línea de aire comprimido o circuito hidráulico',
    diagramContext: 'P&ID / plano de instrumentación de proceso',
  },
  {
    type: 'Sensor',
    category: 'Presión / Caudal',
    subcategory: 'Presión',
    name: 'Presostato',
    signal: 'Contacto NA/NC',
    notes: 'Actúa como interruptor ante un umbral de presión',
    application: 'Activación de alarma o paro de bomba al superar presión límite',
    diagramContext: 'P&ID / plano de instrumentación de proceso',
  },
  {
    type: 'Sensor',
    category: 'Presión / Caudal',
    subcategory: 'Caudal',
    name: 'Caudalímetro tipo turbina',
    signal: 'Pulso o 4–20 mA',
    notes: 'Mide caudal de líquidos',
    application: 'Medición de caudal de agua en circuito de refrigeración',
    diagramContext: 'P&ID / plano de instrumentación de proceso',
  },
  {
    type: 'Sensor',
    category: 'Presión / Caudal',
    subcategory: 'Caudal',
    name: 'Caudalímetro electromagnético',
    signal: '4–20 mA + comunicación digital',
    notes: 'Preciso para líquidos conductivos',
    application: 'Medición de caudal de producto en tubería de proceso',
    diagramContext: 'P&ID / plano de instrumentación de proceso',
  },
  // Nivel
  {
    type: 'Sensor',
    category: 'Nivel',
    subcategory: 'Mecánico',
    name: 'Flotador de nivel',
    signal: 'Contacto NA/NC',
    notes: 'Control sencillo de nivel mínimo/máximo',
    application: 'Protección de bomba por nivel mínimo mediante flotador',
    diagramContext: 'P&ID / plano de instrumentación de proceso',
  },
  {
    type: 'Sensor',
    category: 'Nivel',
    subcategory: 'Capacitivo',
    name: 'Sensor capacitivo de nivel',
    signal: 'Digital 24 V o 4–20 mA',
    notes: 'Mide nivel en sólidos y líquidos',
    application: 'Detección de nivel de granos o polvos en silo',
    diagramContext: 'P&ID / plano de instrumentación de proceso',
  },
  {
    type: 'Sensor',
    category: 'Nivel',
    subcategory: 'Ultrasónico',
    name: 'Sensor de nivel ultrasónico',
    signal: '4–20 mA / 0–10 V',
    notes: 'Mide distancia a la superficie del líquido',
    application: 'Medición de nivel sin contacto en tanque abierto',
    diagramContext: 'P&ID / plano de instrumentación de proceso',
  },
  {
    type: 'Sensor',
    category: 'Nivel',
    subcategory: 'Radar',
    name: 'Sensor de nivel radar',
    signal: '4–20 mA + comunicación',
    notes: 'Alta precisión, poco afectado por vapor o polvo',
    application: 'Control de nivel en tanque de reactores o silos de polvo',
    diagramContext: 'P&ID / plano de instrumentación de proceso',
  },
  // Fuerza / Peso
  {
    type: 'Sensor',
    category: 'Fuerza / Peso',
    subcategory: 'Celda de carga',
    name: 'Celda de carga',
    signal: 'mV/V con acondicionamiento a 4–20 mA',
    notes: 'Uso en básculas y dosificación',
    application: 'Pesaje de tolva de dosificación en planta de mezclas',
    diagramContext: 'P&ID / plano de instrumentación / diagrama de pesaje',
  },
  {
    type: 'Sensor',
    category: 'Fuerza / Peso',
    subcategory: 'Deformación',
    name: 'Strain gauge',
    signal: 'mV/V',
    notes: 'Medición de esfuerzos en estructuras',
    application: 'Monitorización de esfuerzos en estructura metálica o prensa',
    diagramContext: 'P&ID / plano de instrumentación / diagrama de pesaje',
  },
  // Ópticos avanzados
  {
    type: 'Sensor',
    category: 'Ópticos avanzados',
    subcategory: 'Color / Contraste',
    name: 'Sensor de color / contraste',
    signal: 'Salida digital / analógica / bus',
    notes: 'Detección de marcas en packaging, impresión',
    application: 'Detección de marcas de registro en máquinas de impresión',
    diagramContext: 'Plano de control / plano de visión artificial',
  },
  {
    type: 'Sensor',
    category: 'Ópticos avanzados',
    subcategory: 'Identificación',
    name: 'Lector de código de barras o QR',
    signal: 'RS-232 / Ethernet / bus',
    notes: 'Identificación de piezas y productos',
    application: 'Identificación de cajas o pallets por código de barras',
    diagramContext: 'Plano de control / plano de campo',
  },
  {
    type: 'Sensor',
    category: 'Ópticos avanzados',
    subcategory: 'Visión',
    name: 'Cámara industrial / sensor de visión',
    signal: 'Ethernet / bus',
    notes: 'Inspección, medición, conteo, guiado',
    application: 'Inspección de calidad de envases o soldaduras con visión',
    diagramContext: 'Plano de control / plano de visión artificial',
  },
  // Identificación / Distancia
  {
    type: 'Sensor',
    category: 'Identificación / Distancia',
    subcategory: 'RFID',
    name: 'Lector RFID',
    signal: 'Bus industrial / serie',
    notes: 'Seguimiento de pallets, piezas, herramientas',
    application: 'Identificación de pallets en línea de logística mediante tags RFID',
    diagramContext: 'Plano de control / plano de campo',
  },
  {
    type: 'Sensor',
    category: 'Identificación / Distancia',
    subcategory: 'Distancia',
    name: 'Sensor láser de distancia',
    signal: '4–20 mA / bus',
    notes: 'Posicionamiento preciso, medición de perfil',
    application: 'Posicionamiento de carro o medición de perfil de producto',
    diagramContext: 'Plano de control / plano de campo',
  },
  // Ambientales
  {
    type: 'Sensor',
    category: 'Ambientales',
    subcategory: 'Clima',
    name: 'Sensor de temperatura y humedad',
    signal: '4–20 mA / 0–10 V / bus',
    notes: 'Ambientes controlados, almacenes',
    application: 'Control de temperatura y humedad en sala de producción',
    diagramContext: 'Plano de instrumentación / plano de servicios auxiliares',
  },
  {
    type: 'Sensor',
    category: 'Ambientales',
    subcategory: 'Gases',
    name: 'Sensor de gas (CO2, CH4, etc.)',
    signal: '4–20 mA / bus',
    notes: 'Seguridad y control de atmósfera',
    application: 'Detección de fugas de gas en sala de calderas o depósitos',
    diagramContext: 'Plano de instrumentación / plano de servicios auxiliares',
  },
  {
    type: 'Sensor',
    category: 'Ambientales',
    subcategory: 'Luz',
    name: 'Luxómetro / sensor de luz',
    signal: '0–10 V / bus',
    notes: 'Control de iluminación',
    application: 'Control automático de iluminación según nivel de luz ambiente',
    diagramContext: 'Plano de instrumentación / plano de servicios auxiliares',
  },

  // ---- Actuador ----
  // Motores eléctricos
  {
    type: 'Actuador',
    category: 'Motores eléctricos',
    subcategory: 'AC trifásico',
    name: 'Motor AC trifásico + VFD',
    signal: 'Controlado por entradas digitales/analógicas o bus',
    notes: 'Movimiento continuo de cintas, bombas, ventiladores',
    application: 'Accionamiento de cinta transportadora mediante motor trifásico con variador',
    diagramContext: 'Esquema de potencia de motores / P&ID si acciona bomba',
  },
  {
    type: 'Actuador',
    category: 'Motores eléctricos',
    subcategory: 'DC',
    name: 'Motor DC + driver H-bridge',
    signal: 'PWM + dirección desde PLC o micro',
    notes: 'Aplicaciones de baja tensión y control sencillo',
    application: 'Accionamiento de eje pequeño o cinta liviana con control por PWM',
    diagramContext: 'Esquema de potencia de motores / plano de control de máquina',
  },
  {
    type: 'Actuador',
    category: 'Motores eléctricos',
    subcategory: 'Paso a paso',
    name: 'Motor paso a paso + driver',
    signal: 'Entradas STEP/DIR',
    notes: 'Posicionamiento preciso a bajo costo',
    application: 'Posicionamiento de indexador o eje de dosificación con motor paso a paso',
    diagramContext: 'Esquema de potencia de motores / plano de control de motion',
  },
  {
    type: 'Actuador',
    category: 'Motores eléctricos',
    subcategory: 'Servo',
    name: 'Servomotor AC/BLDC',
    signal: 'Entradas de control + feedback de encoder',
    notes: 'Motion control de alta precisión',
    application: 'Control de ejes de robot, pick and place o máquina CNC',
    diagramContext: 'Esquema de potencia de motores / plano de control de motion',
  },
  // Actuadores lineales eléctricos
  {
    type: 'Actuador',
    category: 'Actuadores lineales eléctricos',
    subcategory: 'Cilindro eléctrico',
    name: 'Actuador lineal eléctrico',
    signal: 'Señales de control digitales/analógicas o bus',
    notes: 'Reemplazo de cilindros neumáticos con control preciso de posición',
    application: 'Posicionamiento lineal de tope o empujador con actuador eléctrico',
    diagramContext: 'P&ID / plano de control de máquina',
  },
  // Neumáticos
  {
    type: 'Actuador',
    category: 'Neumáticos',
    subcategory: 'Cilindros',
    name: 'Cilindro neumático simple o doble efecto',
    signal: 'Controlado por válvula neumática',
    notes: 'Movimiento lineal rápido en automatización general',
    application: 'Movimiento de prensas pequeñas, empujadores o pinzas',
    diagramContext: 'P&ID neumático / esquema de mando neumático',
  },
  {
    type: 'Actuador',
    category: 'Neumáticos',
    subcategory: 'Válvulas',
    name: 'Válvula neumática 5/2 o 5/3',
    signal: 'Solenoide 24 VDC',
    notes: 'Control de cilindros y actuadores neumáticos',
    application: 'Conmutación de aire para cilindros en maniobras de máquina',
    diagramContext: 'P&ID neumático / esquema de mando neumático',
  },
  {
    type: 'Actuador',
    category: 'Neumáticos',
    subcategory: 'Pinzas',
    name: 'Pinza neumática',
    signal: 'Controlada por válvula',
    notes: 'Agarre de piezas en robots o manipuladores',
    application: 'Pinza de robot para tomar y soltar piezas en línea de montaje',
    diagramContext: 'P&ID neumático / plano de control de máquina',
  },
  // Hidráulicos
  {
    type: 'Actuador',
    category: 'Hidráulicos',
    subcategory: 'Cilindros',
    name: 'Cilindro hidráulico',
    signal: 'Controlado por válvula hidráulica',
    notes: 'Fuerzas muy elevadas (prensas, maquinaria pesada)',
    application: 'Accionamiento de prensa o pistón de gran fuerza',
    diagramContext: 'P&ID hidráulico / esquema de potencia hidráulica',
  },
  {
    type: 'Actuador',
    category: 'Hidráulicos',
    subcategory: 'Motores',
    name: 'Motor hidráulico',
    signal: 'Control de flujo y presión del aceite',
    notes: 'Movimiento rotativo de alto par',
    application: 'Movimiento de tambor, rueda o winche con motor hidráulico',
    diagramContext: 'P&ID hidráulico / esquema de potencia hidráulica',
  },
  {
    type: 'Actuador',
    category: 'Hidráulicos',
    subcategory: 'Válvulas',
    name: 'Válvula hidráulica direccional o proporcional',
    signal: 'Solenoides controlados desde PLC',
    notes: 'Control de dirección y caudal en sistemas hidráulicos',
    application: 'Control de velocidad y sentido de cilindros y motores hidráulicos',
    diagramContext: 'P&ID hidráulico / esquema de potencia hidráulica',
  },
  // Conmutación de potencia
  {
    type: 'Actuador',
    category: 'Conmutación de potencia',
    subcategory: 'Relés',
    name: 'Relé electromecánico',
    signal: 'Bobina 24 V, contactos NA/NC',
    notes: 'Conmutación de cargas pequeñas o medias',
    application: 'Activación de pequeñas cargas o señales a partir del PLC',
    diagramContext: 'Esquema unifilar / esquema de potencia',
  },
  {
    type: 'Actuador',
    category: 'Conmutación de potencia',
    subcategory: 'Relés',
    name: 'Relé de estado sólido (SSR)',
    signal: 'Entrada 3–32 V, salida AC/DC',
    notes: 'Conmutación sin partes móviles, ideal para maniobras rápidas',
    application: 'Control de resistencias de calefacción con alta frecuencia de conmutación',
    diagramContext: 'Esquema unifilar / esquema de potencia',
  },
  {
    type: 'Actuador',
    category: 'Conmutación de potencia',
    subcategory: 'Contactores',
    name: 'Contactor trifásico',
    signal: 'Bobina 24 V o 220 V',
    notes: 'Conmutación de motores y grandes cargas',
    application: 'Arranque y paro de motores trifásicos en tableros de potencia',
    diagramContext: 'Esquema unifilar / esquema de potencia de motores',
  },
  {
    type: 'Actuador',
    category: 'Conmutación de potencia',
    subcategory: 'Soft-starter',
    name: 'Arrancador suave',
    signal: 'Señales digitales/analógicas desde PLC',
    notes: 'Arranque controlado de motores AC',
    application: 'Reducir picos de corriente y golpes mecánicos al arrancar motores',
    diagramContext: 'Esquema de potencia de motores / plano de control',
  },
  // Válvulas de proceso
  {
    type: 'Actuador',
    category: 'Válvulas de proceso',
    subcategory: 'Válvulas on/off',
    name: 'Válvula de bola o mariposa motorizada',
    signal: '24 VDC/AC, señal de apertura/cierre',
    notes: 'Control de flujo sencillo en tuberías',
    application: 'Apertura y cierre de línea de agua o producto',
    diagramContext: 'P&ID de proceso',
  },
  {
    type: 'Actuador',
    category: 'Válvulas de proceso',
    subcategory: 'Válvulas proporcionales',
    name: 'Válvula de control con actuador eléctrico o neumático',
    signal: 'Señal 4–20 mA / 0–10 V',
    notes: 'Control continuo de caudal, presión, temperatura',
    application: 'Control de caudal de vapor o líquido en lazo PID',
    diagramContext: 'P&ID de proceso',
  },
  {
    type: 'Actuador',
    category: 'Válvulas de proceso',
    subcategory: 'Solenoides',
    name: 'Válvula solenoide',
    signal: 'Bobina 24 VDC/AC',
    notes: 'Control de aire, agua, aceite, etc.',
    application: 'Piloteo de válvulas neumáticas o control directo de fluidos',
    diagramContext: 'P&ID de proceso / esquema de mando neumático',
  },
  // Otros
  {
    type: 'Actuador',
    category: 'Otros',
    subcategory: 'Electroimanes',
    name: 'Electroimán de traba o freno',
    signal: 'Bobina 24 VDC',
    notes: 'Sujeción, bloqueo y frenado de mecanismos',
    application: 'Bloqueo de puertas o freno de ejes mediante electroimán',
    diagramContext: 'Plano de control / esquema de potencia',
  },
  {
    type: 'Actuador',
    category: 'Otros',
    subcategory: 'Frenos/embragues',
    name: 'Freno o embrague electromagnético',
    signal: 'Bobina controlada por PLC',
    notes: 'Acople y desacople de movimiento',
    application: 'Control de acople de eje en máquinas con varias etapas',
    diagramContext: 'Plano de control / esquema de potencia',
  },
  {
    type: 'Actuador',
    category: 'Otros',
    subcategory: 'Señalización',
    name: 'Baliza luminosa o sirena',
    signal: 'Entrada 24 VDC',
    notes: 'Indicadores de estado de máquina y alarmas',
    application: 'Indicación luminosa y sonora de estados RUN/STOP/FALLO',
    diagramContext: 'Frente de máquina / plano de control',
  },
  {
    type: 'Actuador',
    category: 'Otros',
    subcategory: 'Interfaz HMI simple',
    name: 'Pulsadores luminosos / HMI básica',
    signal: 'Entradas/salidas digitales y buses',
    notes: 'Interacción operario–máquina simple',
    application: 'Control local mediante pulsadores iluminados y pequeñas interfaces',
    diagramContext: 'Frente de tablero / diagrama de mando',
  },

  // ---- Display/HMI ----
  // Displays simples
  {
    type: 'Display/HMI',
    category: 'Displays simples',
    subcategory: '7 segmentos / numéricos',
    name: 'Display numérico 7 segmentos',
    signal: 'Entrada desde PLC o indicador (24 V, 4–20 mA, 0–10 V)',
    notes: 'Muestra valores numéricos: velocidad, conteo, temperatura, setpoint',
    application: 'Visualización local de una variable de proceso en frontal de tablero',
    diagramContext: 'Frente de tablero / diagrama de mando',
  },
  {
    type: 'Display/HMI',
    category: 'Displays simples',
    subcategory: 'Bargraph / barra de LEDs',
    name: 'Indicador bargraph de nivel/carga',
    signal: 'Entrada analógica 4–20 mA / 0–10 V',
    notes: 'Representa un valor como barra: nivel, porcentaje, carga',
    application: 'Indicador de nivel o carga mediante barra de LEDs',
    diagramContext: 'Frente de tablero / diagrama de mando',
  },
  // Indicadores de panel
  {
    type: 'Display/HMI',
    category: 'Indicadores de panel',
    subcategory: 'Indicador de proceso',
    name: 'Indicador de proceso de panel',
    signal: 'Entradas 4–20 mA, 0–10 V, PT100, termopar',
    notes: 'Muestra una variable de proceso y puede tener salidas de relé de alarma',
    application: 'Indicador digital de nivel, presión o caudal en puerta de armario',
    diagramContext: 'Frente de tablero / P&ID como instrumento indicador',
  },
  {
    type: 'Display/HMI',
    category: 'Indicadores de panel',
    subcategory: 'Contador / tacómetro',
    name: 'Contador / tacómetro digital',
    signal: 'Entrada de pulsos y salidas de relé o SSR',
    notes: 'Cuenta piezas o mide RPM o frecuencia',
    application: 'Conteo de piezas producidas o medición de RPM en máquina',
    diagramContext: 'Frente de tablero / plano de control',
  },
  // Displays LCD/TFT embebidos
  {
    type: 'Display/HMI',
    category: 'Displays LCD/TFT embebidos',
    subcategory: 'LCD caracteres',
    name: 'LCD 16x2 / 20x4 caracteres',
    signal: 'Bus paralelo tipo HD44780 o I2C/SPI',
    notes: 'Muestra texto simple en sistemas con microcontrolador',
    application: 'Mensajes de estado y parámetros en controladores dedicados',
    diagramContext: 'Plano del equipo / diagrama eléctrico del equipo',
  },
  {
    type: 'Display/HMI',
    category: 'Displays LCD/TFT embebidos',
    subcategory: 'LCD gráfico monocromo',
    name: 'LCD gráfico 128x64',
    signal: 'SPI o bus paralelo',
    notes: 'Dibujo de gráficos simples, iconos y curvas',
    application: 'Visualización de tendencia o estados en controladores específicos',
    diagramContext: 'Plano del equipo / diagrama eléctrico del equipo',
  },
  {
    type: 'Display/HMI',
    category: 'Displays LCD/TFT embebidos',
    subcategory: 'TFT color',
    name: 'Display TFT color',
    signal: 'SPI / RGB / paralelo',
    notes: 'Interfaces gráficas ricas en equipos específicos',
    application: 'Pantalla integrada en variadores o controladores complejos',
    diagramContext: 'Plano del equipo / diagrama eléctrico del equipo',
  },
  // HMI industriales
  {
    type: 'Display/HMI',
    category: 'HMI industriales',
    subcategory: 'HMI texto',
    name: 'HMI de texto con teclado',
    signal: 'RS-232 / RS-485 (Modbus u otros)',
    notes: 'Configuración básica y mensajes de estado desde PLCs compactos',
    application: 'Interfaz con texto para ajustar parámetros y ver mensajes',
    diagramContext: 'Frente de tablero / arquitectura PLC–HMI',
  },
  {
    type: 'Display/HMI',
    category: 'HMI industriales',
    subcategory: 'HMI gráfica táctil',
    name: 'HMI táctil',
    signal: 'Ethernet, Modbus TCP, Profinet, etc.',
    notes: 'Pantallas de operación: recetas, alarmas, tendencias, mandos',
    application: 'Pantalla principal para operar máquina o línea de producción',
    diagramContext: 'Frente de tablero / arquitectura de control',
  },
  {
    type: 'Display/HMI',
    category: 'HMI industriales',
    subcategory: 'HMI con funciones avanzadas',
    name: 'HMI con datalogger o scripts',
    signal: 'Ethernet + puertos adicionales',
    notes: 'Puede registrar datos y ejecutar lógica sencilla',
    application: 'Registro de tendencias y pequeñas automatizaciones desde la HMI',
    diagramContext: 'Frente de tablero / arquitectura de control',
  },
  // PC industrial
  {
    type: 'Display/HMI',
    category: 'PC industrial',
    subcategory: 'Panel PC',
    name: 'Panel PC industrial táctil',
    signal: 'Ethernet, USB y buses según tarjetas',
    notes: 'Corre SCADA o aplicaciones propias',
    application: 'Supervisión de planta o línea completa con SCADA',
    diagramContext: 'Plano de sala de control / arquitectura de red',
  },
  {
    type: 'Display/HMI',
    category: 'PC industrial',
    subcategory: 'Box PC + monitor',
    name: 'PC industrial + monitor',
    signal: 'Ethernet y buses de campo',
    notes: 'PC en armario y monitor en puerta o consola',
    application: 'Supervisión y control HMI–SCADA distribuido',
    diagramContext: 'Plano de sala de control / arquitectura de red',
  },
  // Señalización
  {
    type: 'Display/HMI',
    category: 'Señalización',
    subcategory: 'Torretas / balizas',
    name: 'Baliza luminosa tipo andon',
    signal: 'Entradas digitales 24 V',
    notes: 'Indica estados de máquina por colores',
    application: 'Andon de estado de máquina visible a distancia',
    diagramContext: 'Frente de máquina / plano de control',
  },
  {
    type: 'Display/HMI',
    category: 'Señalización',
    subcategory: 'Scoreboards / Andon',
    name: 'Panel andon / scoreboard',
    signal: 'Entradas digitales o buses industriales/Ethernet',
    notes: 'Muestra producción, objetivos, tiempos de parada',
    application: 'Visualización de producción y objetivos en línea de montaje',
    diagramContext: 'Plano de control / layout de planta',
  },
  {
    type: 'Display/HMI',
    category: 'Señalización',
    subcategory: 'Etiquetas electrónicas',
    name: 'Etiqueta electrónica / e-paper industrial',
    signal: 'Comunicaciones inalámbricas específicas',
    notes: 'Identificación dinámica de ubicaciones o contenedores',
    application: 'Etiquetado electrónico en estanterías de almacén',
    diagramContext: 'Plano de logística / layout de almacén',
  },

  // ---- Dispositivo de mando ----
  // Pulsadores
  {
    type: 'Dispositivo de mando',
    category: 'Pulsadores',
    subcategory: 'Pulsador simple',
    name: 'Pulsador NA (marcha)',
    signal: 'Contacto NA 24 V',
    notes: 'Orden de arranque o marcha de máquina o función',
    application: 'Pulsador verde de marcha en puerta de armario',
    diagramContext: 'Frente de tablero / diagrama de mando',
  },
  {
    type: 'Dispositivo de mando',
    category: 'Pulsadores',
    subcategory: 'Pulsador simple',
    name: 'Pulsador NC (paro)',
    signal: 'Contacto NC 24 V',
    notes: 'Orden de paro normal de máquina o función',
    application: 'Pulsador rojo de paro en el frente del tablero',
    diagramContext: 'Frente de tablero / diagrama de mando',
  },
  {
    type: 'Dispositivo de mando',
    category: 'Pulsadores',
    subcategory: 'Pulsador doble',
    name: 'Pulsador doble marcha/paro',
    signal: 'Dos contactos (NA + NC) 24 V',
    notes: 'Un solo cuerpo con dos funciones diferenciadas',
    application: 'Mando combinado de marcha y paro en un solo dispositivo',
    diagramContext: 'Frente de tablero / diagrama de mando',
  },
  {
    type: 'Dispositivo de mando',
    category: 'Pulsadores',
    subcategory: 'Pulsador luminoso',
    name: 'Pulsador luminoso NA/NC',
    signal: 'Contacto(s) 24 V + lámpara LED',
    notes: 'Combina mando con indicación luminosa de estado',
    application: 'Pulsador iluminado que indica estado de función o máquina',
    diagramContext: 'Frente de tablero / diagrama de mando',
  },
  // Selectores
  {
    type: 'Dispositivo de mando',
    category: 'Selectores',
    subcategory: 'Selector mantenido',
    name: 'Selector 2 posiciones mantenido',
    signal: 'Dos posiciones con contactos NA/NC',
    notes: 'Selección manual/automático o local/remoto',
    application: 'Selector para elegir modo de operación MAN/AUTO',
    diagramContext: 'Frente de tablero / diagrama de mando',
  },
  {
    type: 'Dispositivo de mando',
    category: 'Selectores',
    subcategory: 'Selector mantenido',
    name: 'Selector 3 posiciones mantenido',
    signal: 'Tres posiciones con contactos NA/NC',
    notes: 'Selección de varios modos de operación',
    application: 'Selector para modos paro, manual y automático',
    diagramContext: 'Frente de tablero / diagrama de mando',
  },
  {
    type: 'Dispositivo de mando',
    category: 'Selectores',
    subcategory: 'Selector con retorno',
    name: 'Selector con retorno por resorte',
    signal: 'Posición momentánea y posición(es) mantenida(s)',
    notes: 'Usado para órdenes de jog o impulsos momentáneos',
    application: 'Selector para jog de motor o eje',
    diagramContext: 'Frente de tablero / diagrama de mando',
  },
  // Llaves / Autorización
  {
    type: 'Dispositivo de mando',
    category: 'Llaves / Autorización',
    subcategory: 'Selector a llave',
    name: 'Selector a llave 2 posiciones',
    signal: 'Contactos NA/NC 24 V',
    notes: 'Solo con llave se cambia de modo',
    application: 'Selector a llave para habilitar modo mantenimiento',
    diagramContext: 'Frente de tablero / diagrama de mando y seguridad',
  },
  {
    type: 'Dispositivo de mando',
    category: 'Llaves / Autorización',
    subcategory: 'Selector a llave',
    name: 'Selector a llave 3 posiciones',
    signal: 'Varios contactos NA/NC',
    notes: 'Permite modos restringidos y seguros',
    application: 'Selector a llave para modos operativo, ajuste y mantenimiento',
    diagramContext: 'Frente de tablero / diagrama de mando y seguridad',
  },
  {
    type: 'Dispositivo de mando',
    category: 'Llaves / Autorización',
    subcategory: 'Interruptor de llave simple',
    name: 'Interruptor con llave ON/OFF',
    signal: 'Contacto NA/NC 24 V',
    notes: 'Habilita o bloquea funciones críticas',
    application: 'Bloqueo de habilitación de máquina mediante llave',
    diagramContext: 'Frente de tablero / diagrama de mando y seguridad',
  },
  // Emergencia / Seguridad
  {
    type: 'Dispositivo de mando',
    category: 'Emergencia / Seguridad',
    subcategory: 'Paro de emergencia',
    name: 'Pulsador de emergencia tipo seta enclavado',
    signal: 'Contactos NC de seguridad',
    notes: 'Paro de emergencia de máquina, requiere reset',
    application: 'Sistemas de paro de emergencia en perímetro de máquina',
    diagramContext: 'Plano de seguridad / diagrama de paro de emergencia',
  },
  {
    type: 'Dispositivo de mando',
    category: 'Emergencia / Seguridad',
    subcategory: 'Paro de emergencia',
    name: 'Pulsador de emergencia con llave',
    signal: 'Contactos NC + llave',
    notes: 'Solo personal autorizado puede resetear la emergencia',
    application: 'Paro de emergencia con reset restringido para personal autorizado',
    diagramContext: 'Plano de seguridad / diagrama de paro de emergencia',
  },
  {
    type: 'Dispositivo de mando',
    category: 'Emergencia / Seguridad',
    subcategory: 'Cuerda de paro',
    name: 'Interruptor de cable de emergencia (pull cord)',
    signal: 'Contactos NC en serie de seguridad',
    notes: 'Paro de emergencia en cintas transportadoras largas',
    application: 'Paro de emergencia tipo cuerda a lo largo de cinta transportadora',
    diagramContext: 'Plano de seguridad / P&ID mecánico de transporte',
  },
  {
    type: 'Dispositivo de mando',
    category: 'Emergencia / Seguridad',
    subcategory: 'Interruptor de puerta',
    name: 'Interruptor de puerta de seguridad',
    signal: 'Contactos especiales NC/NA, a menudo codificados',
    notes: 'Detecta apertura de puertas de resguardo',
    application: 'Interbloqueo de puertas de resguardo en máquinas peligrosas',
    diagramContext: 'Plano de seguridad / diagrama de enclavamientos',
  },
  // Pedales / Joysticks
  {
    type: 'Dispositivo de mando',
    category: 'Pedales / Joysticks',
    subcategory: 'Pedal de mando',
    name: 'Pedal simple NA',
    signal: 'Contacto NA 24 V',
    notes: 'Orden momentánea con el pie',
    application: 'Accionamiento de prensas o herramientas con pedal',
    diagramContext: 'Plano de mando local / esquema de control',
  },
  {
    type: 'Dispositivo de mando',
    category: 'Pedales / Joysticks',
    subcategory: 'Pedal de mando',
    name: 'Pedal biestable',
    signal: 'Contactos mantenidos',
    notes: 'Mantiene estado mientras el pedal está pisado o enclavado',
    application: 'Control sostenido de función mientras el operador pisa el pedal',
    diagramContext: 'Plano de mando local / esquema de control',
  },
  {
    type: 'Dispositivo de mando',
    category: 'Pedales / Joysticks',
    subcategory: 'Joystick de mando',
    name: 'Joystick de 2 ejes con contactos',
    signal: 'Varios contactos NA/NC',
    notes: 'Control de grúas, puentes o manipuladores',
    application: 'Mando de puente grúa o manipulador en varias direcciones',
    diagramContext: 'Plano de mando local / esquema de control',
  },
  // Estaciones de mando
  {
    type: 'Dispositivo de mando',
    category: 'Estaciones de mando',
    subcategory: 'Estación de mando fija',
    name: 'Caja de mando con varios pulsadores y selectores',
    signal: 'Conjunto de contactos 24 V',
    notes: 'Agrupa varios dispositivos de mando en un mismo punto',
    application: 'Puesto de mando local con varios botones y selectores',
    diagramContext: 'Plano de mando / layout de la máquina',
  },
  {
    type: 'Dispositivo de mando',
    category: 'Estaciones de mando',
    subcategory: 'Botonera colgante',
    name: 'Botonera colgante para puente grúa',
    signal: 'Contactos NA/NC por botón',
    notes: 'Permite mando desde posición móvil',
    application: 'Botonera para subir/bajar y desplazar puente grúa',
    diagramContext: 'Plano de mando / layout de la máquina',
  },
  {
    type: 'Dispositivo de mando',
    category: 'Estaciones de mando',
    subcategory: 'Panel de operador simple',
    name: 'Panel con pulsadores, selectores y pilotos',
    signal: 'Contactos 24 V + señalización',
    notes: 'Interfaz local básica sin HMI táctil',
    application: 'Panel frontal de máquina con mandos y pilotos',
    diagramContext: 'Frente de tablero / diagrama de mando',
  },
  // Otros dispositivos de mando
  {
    type: 'Dispositivo de mando',
    category: 'Otros dispositivos de mando',
    subcategory: 'Potenciómetro',
    name: 'Potenciómetro de mando (setpoint)',
    signal: 'Entrada analógica (0–10 V / resistencia)',
    notes: 'Ajuste de consignas como velocidad o temperatura',
    application: 'Ajuste manual de velocidad de cinta o setpoint de proceso',
    diagramContext: 'Frente de tablero / diagrama de mando',
  },
  {
    type: 'Dispositivo de mando',
    category: 'Otros dispositivos de mando',
    subcategory: 'Encoder manual',
    name: 'Encoder manual / rueda de pulso',
    signal: 'Pulsos digitales',
    notes: 'Ajuste fino o jog de ejes y valores',
    application: 'Ajuste incremental de posición o parámetros con rueda de pulsos',
    diagramContext: 'Frente de tablero / diagrama de mando',
  },
  {
    type: 'Dispositivo de mando',
    category: 'Otros dispositivos de mando',
    subcategory: 'Teclado numérico',
    name: 'Teclado numérico industrial',
    signal: 'Matriz de contactos o bus',
    notes: 'Entrada de valores numéricos como recetas o contraseñas',
    application: 'Carga de recetas o parámetros numéricos desde panel',
    diagramContext: 'Frente de tablero / diagrama de mando',
  },

  // ---- Equipo de control ----
  // PLC y controladores
  {
    type: 'Equipo de control',
    category: 'PLC y controladores',
    subcategory: 'PLC compacto',
    name: 'PLC compacto / micro-PLC',
    signal: 'Entradas/salidas digitales/analógicas, buses industriales',
    notes: 'Control de máquinas pequeñas y medianas',
    application: 'Automatización de máquina simple con PLC compacto',
    diagramContext: 'Plano de control / esquema de PLC / arquitectura de control',
  },
  {
    type: 'Equipo de control',
    category: 'PLC y controladores',
    subcategory: 'PLC modular',
    name: 'PLC modular',
    signal: 'Módulos de CPU + E/S + comunicación',
    notes: 'Control de líneas de producción y plantas',
    application: 'Automatización de línea completa con PLC modular',
    diagramContext: 'Plano de control / esquema de PLC / arquitectura de control',
  },
  {
    type: 'Equipo de control',
    category: 'PLC y controladores',
    subcategory: 'Módulo de E/S remotas',
    name: 'Módulo de E/S remotas en campo',
    signal: 'Red industrial (Profinet, EtherCAT, Modbus, etc.)',
    notes: 'Acerca las entradas y salidas al proceso reduciendo cableado',
    application: 'Distribución de E/S cerca de máquinas conectadas por red',
    diagramContext: 'Plano de control / arquitectura de control distribuido',
  },
  {
    type: 'Equipo de control',
    category: 'PLC y controladores',
    subcategory: 'Relé de seguridad',
    name: 'Relé o módulo de seguridad',
    signal: 'Entradas seguras + salidas de seguridad',
    notes: 'Gestión segura de setas, cortinas y puertas',
    application: 'Implementación de funciones de parada de emergencia y enclavamientos',
    diagramContext: 'Plano de seguridad / esquema de control de seguridad',
  },
  {
    type: 'Equipo de control',
    category: 'PLC y controladores',
    subcategory: 'Controlador de lazo',
    name: 'Controlador PID de panel',
    signal: 'Entradas de proceso + salidas analógicas/relés',
    notes: 'Control dedicado de temperatura, nivel, presión o caudal',
    application: 'Control autónomo de temperatura de horno o tanque',
    diagramContext: 'P&ID / plano de instrumentación de proceso',
  },

  // ---- Protección / Potencia ----
  // Protección general
  {
    type: 'Protección / Potencia',
    category: 'Protección general',
    subcategory: 'Disyuntor / termomagnético',
    name: 'Interruptor termomagnético',
    signal: 'Protección de línea',
    notes: 'Protege contra sobrecargas y cortocircuitos',
    application: 'Protección de alimentación de tablero o circuitos individuales',
    diagramContext: 'Esquema unifilar / esquema de potencia',
  },
  {
    type: 'Protección / Potencia',
    category: 'Protección general',
    subcategory: 'Fusibles',
    name: 'Fusible / porta-fusible',
    signal: 'Corte por sobrecorriente',
    notes: 'Protección simple y económica de circuitos',
    application: 'Protección local de cargas concretas con fusibles',
    diagramContext: 'Esquema unifilar / esquema de potencia',
  },
  // Protección motor
  {
    type: 'Protección / Potencia',
    category: 'Protección motor',
    subcategory: 'Guardamotor',
    name: 'Guardamotor / interruptor motor',
    signal: 'Protección térmica y magnética de motor',
    notes: 'Protege motores trifásicos frente a sobrecargas y fallos',
    application: 'Protección de motor aguas arriba del contactor',
    diagramContext: 'Esquema de potencia de motores',
  },
  {
    type: 'Protección / Potencia',
    category: 'Protección motor',
    subcategory: 'Relé térmico',
    name: 'Relé térmico para motor',
    signal: 'Contactos auxiliares de fallo',
    notes: 'Se combina con contactores para proteger el motor',
    application: 'Señalización de fallo térmico de motor al PLC',
    diagramContext: 'Esquema de potencia de motores / plano de control',
  },
  // Protección de sobretensión
  {
    type: 'Protección / Potencia',
    category: 'Protección de sobretensión',
    subcategory: 'Supresores de sobretensión',
    name: 'Descargador / varistor / módulo de sobretensión',
    signal: 'Conexión en red de potencia o señales',
    notes: 'Protege contra picos de tensión transitorios',
    application: 'Protección frente a sobretensiones en líneas de alimentación o señales',
    diagramContext: 'Esquema unifilar / plano de protección',
  },

  // ---- Drive / Motion ----
  // Variadores de velocidad
  {
    type: 'Drive / Motion',
    category: 'Variadores de velocidad',
    subcategory: 'VFD / inverter',
    name: 'Variador de frecuencia para motor AC',
    signal: 'Entradas digitales/analógicas + bus',
    notes: 'Control de velocidad y torque de motores AC',
    application: 'Control de velocidad de bombas, ventiladores o cintas',
    diagramContext: 'Esquema de potencia de motores / plano de control',
  },
  // Servodrives
  {
    type: 'Drive / Motion',
    category: 'Servodrives',
    subcategory: 'Servo drive',
    name: 'Amplificador de servomotor',
    signal: 'Bus de campo + feedback encoder',
    notes: 'Control preciso de posición, velocidad y torque',
    application: 'Control de ejes en robots, empaquetadoras o CNC',
    diagramContext: 'Esquema de potencia de motores / plano de control de motion',
  },
  // Motores paso a paso
  {
    type: 'Drive / Motion',
    category: 'Motores paso a paso',
    subcategory: 'Driver de motor paso a paso',
    name: 'Driver stepper',
    signal: 'Entradas STEP/DIR',
    notes: 'Control de motores paso a paso en posicionamiento sencillo',
    application: 'Accionamiento de ejes discretos con motor paso a paso',
    diagramContext: 'Esquema de potencia de motores / plano de control de motion',
  },
  // Arranque de motores
  {
    type: 'Drive / Motion',
    category: 'Arranque de motores',
    subcategory: 'Soft-starter',
    name: 'Arrancador suave de motor',
    signal: 'Entradas de mando desde PLC',
    notes: 'Reduce corrientes de arranque y esfuerzos mecánicos',
    application: 'Arranque suave de compresores, bombas o cintas',
    diagramContext: 'Esquema de potencia de motores / plano de control',
  },

  // ---- Red / Comunicación ----
  // Conmutación Ethernet
  {
    type: 'Red / Comunicación',
    category: 'Conmutación Ethernet',
    subcategory: 'Switch industrial',
    name: 'Switch Ethernet industrial',
    signal: 'Puertos Ethernet RJ45 o M12',
    notes: 'Interconexión de PLCs, HMIs y otros equipos en red',
    application: 'Red de comunicación entre PLCs, HMIs y SCADA',
    diagramContext: 'Plano de red industrial / arquitectura de comunicaciones',
  },
  // Gateways
  {
    type: 'Red / Comunicación',
    category: 'Gateways',
    subcategory: 'Gateway de protocolo',
    name: 'Gateway Modbus, Profinet, CAN, etc.',
    signal: 'Diferentes buses de campo',
    notes: 'Traduce entre distintos protocolos industriales',
    application: 'Conexión de equipos con buses diferentes en una misma planta',
    diagramContext: 'Plano de red industrial / arquitectura de comunicaciones',
  },
  // Seguridad de red
  {
    type: 'Red / Comunicación',
    category: 'Seguridad de red',
    subcategory: 'Router / Firewall industrial',
    name: 'Router o firewall industrial',
    signal: 'Ethernet / WAN',
    notes: 'Segmentación, VPN y seguridad de red de automatización',
    application: 'Conexión segura de red de planta con red corporativa',
    diagramContext: 'Plano de red industrial / arquitectura de comunicaciones',
  },
  // Red inalámbrica
  {
    type: 'Red / Comunicación',
    category: 'Red inalámbrica',
    subcategory: 'Access point industrial',
    name: 'Punto de acceso WiFi industrial',
    signal: 'Ethernet + WiFi',
    notes: 'Conecta equipos móviles o remotos de forma inalámbrica',
    application: 'Comunicación con tablets, máquinas móviles o zonas remotas',
    diagramContext: 'Plano de red industrial / arquitectura de comunicaciones',
  },

  // ---- Alimentación / Energía ----
  // Fuentes
  {
    type: 'Alimentación / Energía',
    category: 'Fuentes',
    subcategory: 'Fuente 24 VDC riel DIN',
    name: 'Fuente conmutada 24 VDC',
    signal: 'Entrada 230 VAC → salida 24 VDC',
    notes: 'Alimenta PLC, sensores y actuadores de baja potencia',
    application: 'Alimentación principal de circuito de control a 24 V',
    diagramContext: 'Esquema unifilar / plano de alimentación de control',
  },
  {
    type: 'Alimentación / Energía',
    category: 'Fuentes',
    subcategory: 'Convertidor DC/DC',
    name: 'Módulo DC/DC (por ejemplo 24 → 5 V)',
    signal: 'Entrada DC → salida DC regulada',
    notes: 'Genera tensiones auxiliares para electrónica',
    application: 'Alimentación de electrónica a 5 V o 12 V desde 24 V',
    diagramContext: 'Esquema de alimentación de control / detalle de electrónica',
  },
  // Calidad de energía
  {
    type: 'Alimentación / Energía',
    category: 'Calidad de energía',
    subcategory: 'UPS / SAI',
    name: 'UPS industrial',
    signal: 'Entrada/salida AC, a veces DC',
    notes: 'Mantiene activos PLC, PC y HMI ante cortes de energía',
    application: 'Continuidad de servicio para sistemas críticos de control',
    diagramContext: 'Esquema unifilar / plano de alimentación',
  },
  // Monitores
  {
    type: 'Alimentación / Energía',
    category: 'Monitores',
    subcategory: 'Relé de control de tensión/fase',
    name: 'Relé de control de fase/tensión',
    signal: 'Monitorea red trifásica o monofásica',
    notes: 'Detecta fallo de fase, orden incorrecta o sub/sobretensión',
    application: 'Protección de motores y equipos frente a fallos de red',
    diagramContext: 'Esquema unifilar / plano de protección',
  },

  // ---- Infraestructura / Montaje ----
  // Gabinetes
  {
    type: 'Infraestructura / Montaje',
    category: 'Gabinetes',
    subcategory: 'Gabinete / armario',
    name: 'Armario eléctrico industrial',
    signal: 'N/A (elemento mecánico)',
    notes: 'Aloja y protege componentes eléctricos y electrónicos',
    application: 'Tablero principal de control y potencia',
    diagramContext: 'Plano de armario / layout mecánico',
  },
  {
    type: 'Infraestructura / Montaje',
    category: 'Gabinetes',
    subcategory: 'Caja de conexión',
    name: 'Caja de conexiones IP65/IP67',
    signal: 'N/A',
    notes: 'Conexión y distribución de señales cerca del proceso',
    application: 'Cajas de derivación y empalme de sensores y actuadores',
    diagramContext: 'Plano de campo / layout de planta',
  },
  // Conexión
  {
    type: 'Infraestructura / Montaje',
    category: 'Conexión',
    subcategory: 'Bornes / regletas',
    name: 'Regleta / bornera en riel DIN',
    signal: 'Conexión de conductores',
    notes: 'Facilita el cableado y mantenimiento',
    application: 'Interconexión de cables de campo con cables de tablero',
    diagramContext: 'Plano de armario / diagrama de cableado',
  },
  {
    type: 'Infraestructura / Montaje',
    category: 'Conexión',
    subcategory: 'Conectores circulares',
    name: 'Conectores M8/M12',
    signal: 'Conexión enchufable de sensores/actuadores',
    notes: 'Permiten conexión rápida y robusta en campo',
    application: 'Conexión de sensores y actuadores en máquinas modulares',
    diagramContext: 'Plano de campo / diagramas de conexionado',
  },
  // Canalización
  {
    type: 'Infraestructura / Montaje',
    category: 'Canalización',
    subcategory: 'Canaletas / bandejas / prensaestopas',
    name: 'Canaleta, bandeja portacables, prensaestopas',
    signal: 'N/A',
    notes: 'Guiado y entrada de cables al armario y entre equipos',
    application: 'Gestión de cables entre armario y campo',
    diagramContext: 'Plano de armario / layout mecánico / plano de cableado',
  },

  // ---- Instrumentación de proceso ----
  // Transmisores inteligentes
  {
    type: 'Instrumentación de proceso',
    category: 'Transmisores inteligentes',
    subcategory: 'Transmisor de presión',
    name: 'Transmisor de presión inteligente',
    signal: '4–20 mA + HART o fieldbus',
    notes: 'Mide presión con diagnóstico y comunicación avanzada',
    application: 'Medición de presión en procesos críticos con diagnóstico adicional',
    diagramContext: 'P&ID / plano de instrumentación de planta',
  },
  {
    type: 'Instrumentación de proceso',
    category: 'Transmisores inteligentes',
    subcategory: 'Transmisor de nivel',
    name: 'Transmisor de nivel radar/ultrasónico',
    signal: '4–20 mA + comunicación digital',
    notes: 'Mide nivel en tanques con alta fiabilidad',
    application: 'Control de nivel en tanques de producto o reactores',
    diagramContext: 'P&ID / plano de instrumentación de planta',
  },
  {
    type: 'Instrumentación de proceso',
    category: 'Transmisores inteligentes',
    subcategory: 'Transmisor de caudal',
    name: 'Caudalímetro electromagnético o coriolis',
    signal: '4–20 mA + fieldbus',
    notes: 'Medición de caudal precisa en procesos',
    application: 'Medición de caudal de producto en líneas de proceso continuo',
    diagramContext: 'P&ID / plano de instrumentación de planta',
  },
  // Analizadores
  {
    type: 'Instrumentación de proceso',
    category: 'Analizadores',
    subcategory: 'Analizador químico',
    name: 'Analizador de pH, conductividad u oxígeno disuelto',
    signal: '4–20 mA + comunicación',
    notes: 'Controla calidad de agua o procesos químicos',
    application: 'Control de calidad de agua de calderas, efluentes o procesos químicos',
    diagramContext: 'P&ID / plano de instrumentación de planta',
  },
  // Registro de datos
  {
    type: 'Instrumentación de proceso',
    category: 'Registro de datos',
    subcategory: 'Datalogger / registrador',
    name: 'Registrador de datos independiente',
    signal: 'Entradas analógicas/digitales + memoria',
    notes: 'Registro histórico de variables de proceso sin PC',
    application: 'Registro local de tendencias de temperatura, presión o caudal',
    diagramContext: 'P&ID / plano de instrumentación / documentación de planta',
  },
]
